### ISSUE TITLE
Question: Slowness in the consumer polling config Info -> One Producer-One Topic-One Partition-One Consumer

### ISSUE THREAD

**Issue by Udayaprasad** [confluentinc/confluent-kafka-python#1077]
Description
===========

I have the following situation with my consumer_app code.

Producer code pushes the sequence of image frames from Video (cv2.VideoOpened()) to a single Topic having a single partition (To maintain image sequences we had set unique key while producing images)

Consumer code has one Consumer (basically one consumer Thread having a unique Group ID)

Sometimes the consumer polling is fast enough (0.000108 seconds), but sometimes it is taking more than 15 seconds to download the data.

@edenhill  Please suggest

![image](https://user-images.githubusercontent.com/8266316/112999135-4f7d6900-918c-11eb-8dc9-79c1a742114b.png)

```
environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:4703
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LOG_SEGMENT_BYTES: 536870912
      KAFKA_LOG_RETENTION_BYTES: 5368709128
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_MESSAGE_MAX_BYTES: 30000036
      KAFKA_NUM_IO_THREADS: 24
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_NUM_REPLICA_FETCHERS: 3
      KAFKA_REPLICA_FETCH_MAX_BYTES: 30000036
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  ```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ X] confluent-kafka-python and librdkafka version (1.5.0):
 - [ X] Apache Kafka broker version (confluentinc/cp-kafka:5.5.3):
 - [ X] Client configuration: `{
                "enable.auto.commit": true,
                "auto.offset.reset": "latest"}`
 - [X ] Operating system (Ubuntu 18):
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ X] Critical issue
