### ISSUE TITLE
Losing refcount of None when using message.headers()

### ISSUE THREAD

**Issue by krkapes** [confluentinc/confluent-kafka-python#1191]
Description
===========
Method message.headers() is returning a list of [(key, value)] pairs, and if any of this values is None, reference count for None is not increased and on the end application crashes with error :

`
Fatal Python error: deallocating None

Current thread 0x00007fba91843740 (most recent call first):
  File "consumer.py", line 17 in run_consumer
  File "consumer.py", line 23 in <module>
Aborted
`

The doc says: 
[https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Producer.produce](url)
> dict|list (headers) – Message headers to set on the message. The header key must be a string while the value must be binary, unicode or None. 

There should not be a issue with producing None as header value.

How to reproduce
================
docker-compose.yaml for the broker/zookeeper setup

```
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
```

**PRODUCER**
```

from confluent_kafka import Producer
import time

def run_producer():
	conf = {
	'bootstrap.servers':'localhost:9092'
	}

	producer = Producer(conf)

	for c, x in enumerate(range(10000)):
		print("producing")
		headers = {"h1":b'1', 'h2':'b2'}
		msg = "ref count will not drop"
		if c % 2 !=0:
			headers["h3"] = None
			msg = "ref count will drop"
		producer.produce('test-topic',value=msg, key=b'10',headers=headers)
		print("Flushing")
		producer.flush()
		print("Flushed")

	print("DONE")


if __name__ == "__main__":
	run_producer()
```

CONSUMER
```
from confluent_kafka import Consumer
import time
import sys

def run_consumer():
	conf = {
	'bootstrap.servers':'localhost:9092',
	'enable.auto.commit':False,
	'group.id':str(time.time())
	}

	consumer = Consumer(conf)
	consumer.subscribe(["test-topic"])
	print("ref count before",sys.getrefcount(None))
	for x in range(100000):
		msg = consumer.poll()
		print("REF COUNT", sys.getrefcount(None))
		print("HEADERS", msg.value())
		print("HEADERS", msg.headers())

if __name__ == "__main__":
	run_consumer()
```

Error:
```

HEADERS b'ref count will drop'
HEADERS [('h1', b'1'), ('h2', b'b2'), ('h3', None)]
REF COUNT 5
HEADERS b'ref count will not drop'
HEADERS [('h1', b'1'), ('h2', b'b2')]
REF COUNT 5
HEADERS b'ref count will drop'
HEADERS [('h1', b'1'), ('h2', b'b2'), ('h3', None)]
REF COUNT 4
HEADERS b'ref count will not drop'
HEADERS [('h1', b'1'), ('h2', b'b2')]
REF COUNT 4
HEADERS b'ref count will drop'
HEADERS [('h1', b'1'), ('h2', b'b2'), ('h3', None)]
REF COUNT 3
HEADERS b'ref count will not drop'
HEADERS [('h1', b'1'), ('h2', b'b2')]
REF COUNT 3
HEADERS b'ref count will drop'
HEADERS [('h1', b'1'), ('h2', b'b2'), ('h3', None)]
REF COUNT 2
HEADERS b'ref count will not drop'
HEADERS [('h1', b'1'), ('h2', b'b2')]
REF COUNT 2
HEADERS b'ref count will drop'
HEADERS [('h1', b'1'), ('h2', b'b2'), ('h3', None)]
Fatal Python error: deallocating None

Current thread 0x00007f19612ad740 (most recent call first):
  File "consumer.py", line 17 in run_consumer
  File "consumer.py", line 23 in <module>
Aborted

```

Checklist
=========

I'm using: 
confluent-kafka==1.2.0
libdrkafka == v1.3.0
python == 3.7

As application is running in docker, here is python docker that is used:
python:3.7-slim-buster

Additionally,
this was reproduced with latest python 3.9.6 and also with confluent-kafka 1.6.1 and librdkafka v1.6.1
