### ISSUE TITLE
not consuming

### ISSUE THREAD

**Issue by saleemalharir1** [confluentinc/confluent-kafka-python#1622]
Description
===========
i have kafka server running on my local machine using docker, the problem is that i am not able to consume messages from outside the network 
i have opened all the necessary ports in my router 
if i am inside the network i can produce and consume i will attach the consumer code and producer code here 

here is the consumer code 
``` from kafka import KafkaConsumer
import json

try:
    # Set up Kafka consumer
    consumer = KafkaConsumer('my_topic', bootstrap_servers=['ip_address:9092'],)
    print("Consumer Properties:", consumer.config)

    # Iterate over messages in the topic
    for message in consumer:
        # Decode message from bytes to string
        message_value = message.value.decode('utf-8')
        print(message_value)
        # ...rest of the code...
except Exception as e:
    print("Error:", e)
```
and here is the producer code 

```
from kafka import KafkaProducer
import time

def send_numbers():
    # Configure Kafka producer
    producer = KafkaProducer(bootstrap_servers='ip_address:9092')

    # Send numbers 1 to 100 to Kafka topic
    for num in range(1, 101):
        # Convert number to bytes
        value = str(num).encode('utf-8')
        
        # Send the message to the Kafka topic
        producer.send('my_topic', value=value)
        print(value)
        # Wait for a moment
        time.sleep(0.1)

    # Flush and close the producer
    producer.flush()
    producer.close()

# Call the function to send numbers
send_numbers()
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by saleemalharir1** [comment]
here is my kafka.yaml

```
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.2 # this need to be your ip address or where you are planning to run your kafka server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

volumes:
  elasticsearch-data-volume:
    driver: local
```
