### ISSUE TITLE
Failed to resolve address for boostrap.servers in docker

### ISSUE THREAD

**Issue by arnold-jr** [confluentinc/confluent-kafka-python#452]
Description
===========
I am not able to access the kafka broker running on my docker user-bridged network. However, the Python telnet utility is able to resolve the address.

How to reproduce
================

Running docker-for-mac, my docker kafka setup:
```bash
docker network create my-net

docker run -d --name zookeeper -p 2181:2181 --network my-net confluent/zookeeper

docker run -d --name kafka -p 9092:9092 --network my-net confluent/kafka

docker run -d --name schema-registry -p 8081:8081 --network my-net confluent/schema-registry

docker run -d --name rest-proxy -p 8082:8082 --network my-net confluent/rest-proxy

```

My custom Dockerfile:
```bash
FROM alpine:edge

COPY . /root 

WORKDIR /root

RUN apk add --no-cache python3-dev libstdc++ py3-setuptools && \
  apk add --no-cache librdkafka-dev && \
  apk add --no-cache --virtual .build-deps g++ && \
  apk add --no-cache bash git openssh

RUN pip3 install --upgrade pip && \
  pip3 install --no-binary :all: confluent-kafka

```

From the python3 cli:
```
>>> from confluent_kafka import Producer
>>> p = Producer({'bootstrap.servers': 'kafka'})
>>> %3|1537384207.617|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Address not available
%3|1537384207.617|ERROR|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Address not available
%3|1537384207.617|ERROR|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down

>>> from telnetlib import Telnet
>>> with Telnet('kafka', 9092) as tn:
...   tn.read_eager()
...
b''
>>>
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): >>> ```confluent_kafka.libversion()
('0.11.5', 722431)
>>> confluent_kafka.version()
('0.11.5', 722176)```
 - [ ] Apache Kafka broker version: 0.10.0.0-cp1
 - [ ] Client configuration: `{...}`
 - [x] Operating system: `alpine:edge` on docker-for-mac
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Provide broker log excerpts: nothing in response to trying to connect
 - [ ] Critical issue

**Comment by mhowlett** [comment]
[at a quick glance] it looks like you need to set the `advertised.listeners` broker config. This blog post might be helpful: https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by arnold-jr** [comment]
@mhowlett Thanks for the quick response and the link to the blog. I threw everything into a a docker compose file but am still not able to resolve:
```yaml
version: '3.7'
services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    networks: 
      - confluent
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181 
  
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    networks:
      - confluent
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
  
  pythonproducer:
    image: docker-registry:443/synthnotes-kafka-python-producer:latest 
    networks:
      - confluent
    depends_on:
      - kafka
    entrypoint: python3 produce.py -b kafka:29092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 

networks:
  confluent:
    driver: bridge

```

No combinations of listeners for the `-b` option work in this setup. Since I'm defining the client service within the `confluent` network, I should be able to use an internal listener, no?
