### ISSUE TITLE
using multiple consumers in consumer group

### ISSUE THREAD

**Issue by gbakthavatchalam** [confluentinc/confluent-kafka-python#872]
Issue
-----
Unable to balance load across 2 consumers in a single consumer group. Only 1 consumer is able to pull the messages from the topic while the other consumer is stagnant.

Description
===========
I have one topic with 3 partitions.
I am trying to read messages from the topic using 2 consumers simultaneously.
I am using a dockerized confluent kafka image

docker-compose
============
```
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

topic creation
==========
`docker-compose exec kafka kafka-topics --create --topic jobs --partitions 3 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181`

How to reproduce
==============

how I create a producer
==================
p = Producer({'bootstrap.servers': f'{KAFKA_HOST}:{KAFKA_PORT}'})

how I create a Consumer
==================
consumer_settings = {
	'bootstrap.servers': f'{KAFKA_HOST}:{KAFKA_PORT}',
	'group.id': KAFKA_GROUP,
	'auto.offset.reset': 'earliest',
	'auto.commit.interval.ms': 1,
	'enable.auto.commit': True
}

c = Consumer(settings)
c.subscribe([topic])

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): latest
 - [ ] Apache Kafka broker version: latest
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Mac
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Please suggest
