### ISSUE TITLE
Cannot connect kafka when I run python script in docker : Failed to resolve 'kafka002:9092': Name or service not known

### ISSUE THREAD

**Issue by DachuanZhao** [confluentinc/confluent-kafka-python#947]
Description
===========
My kafka cluster is in ECS . I can connect the cluster in my linux , but I can't connect the cluster in linux's docker . 

How to reproduce
================
docker yml
```yml
version: '3'
services:

  ranking1:
    container_name: ranking_engine_tornado
    image: registry.cn-beijing.aliyuncs.com/xxxx/xxxxxx
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - init_conf1
#      - init_conf2
#    network_mode: "host"
    ports:
      - 8111:8111
      - 8112:8112
      - 8113:8113
      - 8114:8114
    command: supervisord -c /etc/supervisord.conf -n

  ranking2:
    container_name: ranking_engine_python
    image: registry.cn-beijing.aliyuncs.com/xxxx/xxxxxx
    volumes:
      - .:/code
    working_dir: /code
#    network_mode: "host"
    command: python /code/test/docker_test.py

  init_conf1: 
    container_name: ranking_init_conf
    image: registry.cn-beijing.aliyuncs.com/xxxx/xxxxxx
    volumes:
      - .:/code
    working_dir: /code
    network_mode: "host"
    command: unlink /var/run/supervisor.sock
```
Python file : 
```Python
class KafkaClient():

    def __init__(self,topic_list:list,group_id:str=None):
        self.group_id = group_id
        self.topic_list = topic_list

    def init_consumer(self,conf,offset=0):
        if self.group_id is None:
            self.group_id = str(uuid.uuid1())
        host_list = [ip1,ip2,ip3]
        port = 9092
        host_list = ["{}:{}".format(v,port) for v in host_list]
        self.host = ",".join(host_list)
        conf_dict = {
            'bootstrap.servers': self.host,
            "group.id": self.group_id,
            'auto.offset.reset': 'smallest',
            'enable.auto.commit': True,
            'default.topic.config': {'auto.offset.reset': 'smallest'},
        }
        self.consumer = confluent_kafka.Consumer(conf_dict)
        self.consumer.subscribe(self.topic_list)



kafka_client = KafkaClient(topic_List, group_id=group_id)

```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
python : 3.7.7
confluent_kafka.__version__ = 1.5.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
centOS 7 
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
```
| %3|1599118915.035|FAIL|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator: Failed to resolve 'kafka002:9092': Name or service not known (after 8ms in state CONNECT, 8 identical error(s) suppressed)
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by DachuanZhao** [comment]
> https://rmoff.net/2018/08/02/kafka-listeners-explained/

Hi , I also notice this [https://github.com/confluentinc/confluent-kafka-python/issues/452](https://github.com/confluentinc/confluent-kafka-python/issues/452) . Counld you please give me the answer rather than a document ? 💯 

Should I add the line 
```
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
```
in docker.yml ?

**Comment by Chloejay** [comment]
I had the same issue before, you should config your broker container in your docker.yml file. this doc sent above is well explained. so just change to `KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://your_cloud_host:9092`, based on context your run docker on alicloud (where your client to access to broker).

**Comment by glaucocustodio** [comment]
I was able to get Kafka working in Docker with the following docker-compose.yml file:
```
version: '2'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
```

You need to have `127.0.0.1 kafka` in the `/etc/hosts` file
